version: '3.5'

networks:
  stone-eai:
    name: stone-eai

volumes:
  prometheus_data: 
  grafana_data: 

services:    
  prometheus:
    image: stone/prometheus:1.0.0
    container_name: prometheus
    volumes:
      - prometheus_data:/prometheus
    expose:
      - 9090
    ports:
      - "9090:9090"
    networks:
      - stone-eai

  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
        - GF_SECURITY_ADMIN_PASSWORD=pass
    depends_on:
        - prometheus
    ports:
        - "3000:3000"
    networks:
      - stone-eai