scrape_configs:
  - job_name:       'wildfly-camel'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 30s

    static_configs:
      - targets: ['wildfly-camel:9393']
        labels:
          group: 'production'