version: '3.5'

networks:
  stone-eai:
    external:
      name: stone-eai

volumes:
  wildfly-content: 
  wildfly-config: 
  wildfly-deployments: 
  artemis-data: 
  postgres:

services:
  wildfly-camel:
    image: stone/wildfly-camel:1.0.0
    container_name: wildfly-camel
    volumes: 
      - wildfly-content:/wildfly/standalone/data/content
      - wildfly-content:/wildfly/standalone/deployments
      - wildfly-config:/wildfly/standalone/configuration
      - artemis-data:/wildfly/standalone/data/activemq
    expose:
      - 8080
      - 9990
      - 9393
    ports:
      - "8080:8080"
      - "8787:8787"
      - "9990:9990"
      - "9393:9393"
    networks:
      - stone-eai
    environment:
      - DEBUG=true

  postgres:
    image: postgres
    container_name: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=admin
    expose:
      - 5432
    ports:
      - "5432:5432"
    networks:
      - stone-eai
